### PR TITLE
make base58 alphabet publicly available for user code

### PR DESCRIPTION
**Pull request by JFixby**

### CODE REVIEW

**Comment by dajohi** [comment]
@Jfixby is this needed for something in particular?

**Comment by JFixby** [comment]
The real question is why it is private in the first place. (answer: for no real reason)
 
My interest here is to access the alphabet for to build magics:
```Go
func magicForPrefix(desiredPrefix string, size int) (string, string) {
	topChar := base58.Alphabet[len(base58.Alphabet)-1:]
	firstChar := base58.Alphabet[0:1]
	min := desiredPrefix + preFillString(size, firstChar)
	max := desiredPrefix + preFillString(size, topChar)
 	left := base58.Decode(min)[0:2]
	right := base58.Decode(max)[0:2]
 	l := binary.BigEndian.Uint16(left)
	r := binary.BigEndian.Uint16(right)
 	L := lang.MinInt(l, r)
	L++
	R := lang.MaxInt(l, r)
	R--
	if L > R {
		lang.ReportErr("Failed to find magic")
	}
 	magic := uint16(L)
	bs := make([]byte, 2)
	binary.BigEndian.PutUint16(bs, magic)
 	H1 := fmt.Sprintf("0x%02x", bs[0])
	H2 := fmt.Sprintf("0x%02x", bs[1])
 	return H1, H2
}
```

**Comment by alexlyp** [comment]
how about you do add an Alphabet() func that returns the private alphabet?

**Comment by davecgh** [comment]
Closing this because there does not appear any desire for this among the larger community.

**Pull request closed without merging**
